### Get all prouducts
GET http://localhost:5000/api/products

### GET single product
GET   http://localhost:5000/api/products/64ad5e7e30c60ba8498a6f27

### Register user
POST http://localhost:5000/api/users
content-type: application/json

{
  "name": "Jan Esser",
  "email": "jan.esser@posteo.de",
  "password": "123456"
}

### Login user
POST http://localhost:5000/api/users/auth
content-type: application/json

{
  "email": "john@gmail.com",
  "password": "123456"
}

### Login admin 
POST http://localhost:5000/api/users/auth
content-type: application/json

{
  "email": "admin@email.com",
  "password": "123456"
}

### Logout user
POST http://localhost:5000/api/users/logout

### Get User Profile
GET http://localhost:5000/api/users/profile

### Update User Profile
PUT http://localhost:5000/api/users/profile
content-type: application/json

{
  "email": "john@email.com"
}

### Get users / admin
GET http://localhost:5000/api/users

### Get user by id / admin
GET http://localhost:5000/api/users/64ad5e7e30c60ba8498a6f23

### Delete user 
DELETE http://localhost:5000/api/users/64ad5e7e30c60ba8498a6f23

### Update user 
PUT http://localhost:5000/api/users/64ad5e7e30c60ba8498a6f23
content-type: application/json

{
  "email": "john@email.com"
}

### Create new order
POST http://localhost:5000/api/orders

### Get logged in user orders / admin 
GET http://localhost:5000/api/orders/my

### Get order by id / admin
GET http://localhost:5000/api/orders/:id

### Update order to paid 
PUT http://localhost:5000/api/orders/:id/pay

### Update to delivered / admin
PUT http://localhost:5000/api/orders/:id/deliver

### Get all orders / admin
GET http://localhost:5000/api/orders

